 # 配置数据库连接池
spring:
  jpa:
    show-sql: true
    database: mysql
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans : true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username : root
    password : root

security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: test
      grant-type: client_credentials
      scope: server
    resource:
      id: account-service




