logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 80000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-center

security:
  oauth2:
    authorization:
      check-token-access: http://localhost:4000/uaa/oauth/check_token
    client:
      access-token-uri: http://localhost:4000/uaa/oauth/token
      user-authorization-uri: http://localhost:4000/uaa/oauth/authorize
    resource:
      user-info-uri: http://localhost:4000/uaa/user
      prefer-token-info: false


